### ISSUE TITLE
Need to rebase more than one path per once

### ISSUE THREAD

**Issue by ttim** [pantsbuild/zincutils#8]
Pants will rebase two paths instead of previous one: build root path and work directory path. So we need some API to express this intention in zincutils. Currently pants executes rebase_from_path twice which can be inefficiently.

**Comment by peiyuwang** [comment]
https://rbcommons.com/s/twitter/r/4352/ is to address this (note in pants repo because zincutils has been merged into pants repo)

**Comment by peiyuwang** [comment]
Reviewed at https://rbcommons.com/s/twitter/r/4352/

Committed as 04afcc8476afd5bbff6326485bfb1f66b39b3d72
